### PR TITLE
Check if ped is in vehicle to prevent broken animations

### PR DESCRIPTION
**Pull request by samtoxie**
Check if ped is in vehicle to prevent broken animations (Mainly noticeable on vehicles like cabrios and (motor)cycles)

### CODE REVIEW

**Comment by Senlar** [comment]
Why not move the vehicle check up into the IF so it doesn't even try loading the animdict?

**Comment by samtoxie** [comment]
> Why not move the vehicle check up into the IF so it doesn't even try loading the animdict?

You're right, i've changed it

**Comment by FrazzIe** [comment]
sanchez (motorcycle): https://i.imgur.com/uMkWzD1.png
9F Cabrio: https://i.imgur.com/39s8IEc.png

I personally don't see anything wrong with the animation for the vehicles/types of vehicles you mentioned?

**Comment by samtoxie** [comment]
> 
> 
> sanchez (motorcycle): https://i.imgur.com/uMkWzD1.png
> 9F Cabrio: https://i.imgur.com/39s8IEc.png
> 
> I personally don't see anything wrong with the animation for the vehicles/types of vehicles you mentioned?

Yes now that I think of it, it is when you are using the shoulder-radio animation. However because I never really used the plugin myself other than fixing this for a friend I'm not sure if he changed the animation himself or that it is a parameter within your plugin to use it. If it is the last a check could be added so it only stops it when using that animation.

It is this animation, but when you use it in a vehicle the arm does the weird twisty thing.
maxresdefault

if this animation isn't something provided by the plugin itself feel free to ignore it. I just didn't realize then he changed the animation himself to that instead of the default one.

**Comment by FrazzIe** [comment]
That animation is in the script but is behind a config option, i'll take a look at it

**Pull request closed without merging**
